package com.cootek.smartinput5.p066ui.schema.template;

import com.cootek.smartinput5.engine.Settings;
import com.cootek.smartinput5.p066ui.EnterKey;
import com.cootek.smartinput5.p066ui.schema.C2944b;
import com.cootek.smartinput5.p066ui.schema.KeyboardSchema;
import com.cootek.smartinput5.p066ui.schema.RowSchema;

/* renamed from: com.cootek.smartinput5.ui.schema.template.T_chs_handwrite_full */
public class T_chs_handwrite_full extends KeyboardSchema {
    public T_chs_handwrite_full() {
        this.height = "fraction/hwfull_keyboard_height";
        this.slipThreshold = "60%p";
        this.shadowRect = "0%p:0%p:100%p:50%p,10%p:50%p:100%p:100%p";
        this.supportSmileyAnimation = "false";
        RowSchema rowSchema = new RowSchema();
        C2944b bVar = new C2944b();
        bVar.keyName = "sk_half";
        bVar.backgroundType = "fun";
        bVar.mainOnlyTextSize = "dimen/button_textsize";
        bVar.keyWidth = "fraction/bottom_key_width_2";
        bVar.keyType = "Key";
        C2944b bVar2 = new C2944b();
        bVar2.keyName = "Comma";
        bVar2.backgroundType = "fun";
        bVar2.keyWidth = "16.25%p";
        bVar2.keyType = "Key";
        C2944b bVar3 = new C2944b();
        bVar3.keyName = "Dot";
        bVar3.backgroundType = "fun";
        bVar3.keyWidth = "16.25%p";
        bVar3.keyType = "Key";
        C2944b bVar4 = new C2944b();
        bVar4.keyName = "QuestionMark";
        bVar4.backgroundType = "fun";
        bVar4.keyWidth = "16.25%p";
        bVar4.keyType = "Key";
        C2944b bVar5 = new C2944b();
        bVar5.keyName = "ExclamationMark";
        bVar5.backgroundType = "fun";
        bVar5.keyWidth = "16.25%p";
        bVar5.keyType = "Key";
        C2944b bVar6 = new C2944b();
        bVar6.keyName = "sk_bk";
        bVar6.backgroundType = "fun";
        bVar6.keyIcon = "drawable/key_fore_backspace";
        bVar6.keyEdgeFlags = Settings.KEYBOARD_MARGIN_RIGHT;
        bVar6.keyType = "Key";
        rowSchema.keys = new C2944b[]{bVar, bVar2, bVar3, bVar4, bVar5, bVar6};
        RowSchema rowSchema2 = new RowSchema();
        rowSchema2.rowEdgeFlags = "bottom";
        C2944b bVar7 = new C2944b();
        bVar7.keyName = "sk_sym";
        bVar7.backgroundType = "fun";
        bVar7.keyEdgeFlags = Settings.KEYBOARD_MARGIN_LEFT;
        bVar7.mainOnlyTextSize = "dimen/button_textsize";
        bVar7.keyWidth = "fraction/bottom_key_width_2";
        bVar7.keyType = "Key";
        C2944b bVar8 = new C2944b();
        bVar8.keyName = "sk_lng";
        bVar8.backgroundType = "fun";
        bVar8.triType = "opt_curve";
        bVar8.foregroundType = "fitCenter";
        bVar8.hasLongPressIcon = "true";
        bVar8.mainOnlyTextSize = "dimen/button_textsize";
        bVar8.keyWidth = "fraction/bottom_key_width_1";
        bVar8.keyType = "LanguageKey";
        C2944b bVar9 = new C2944b();
        bVar9.keyName = "sk_sp";
        bVar9.foregroundType = "fitCenter";
        bVar9.keyIcon = "@drawable/key_sp_normal";
        bVar9.iconPreview = "drawable/key_preview_space";
        bVar9.mainOnlyTextSize = "@dimen/space_button_textsize";
        bVar9.keyWidth = "42%p";
        bVar9.keyType = "SpaceKey";
        C2944b bVar10 = new C2944b();
        bVar10.keyName = "sk_num";
        bVar10.backgroundType = "fun";
        bVar10.keyWidth = "fraction/bottom_key_width_9";
        bVar10.keyType = "Key";
        C2944b bVar11 = new C2944b();
        bVar11.keyName = "sk_ent";
        bVar11.backgroundType = "fun";
        bVar11.keyIcon = "@drawable/key_fore_enter";
        bVar11.keyEdgeFlags = Settings.KEYBOARD_MARGIN_RIGHT;
        bVar11.mainOnlyTextSize = "dimen/button_textsize";
        bVar11.keyWidth = "fraction/bottom_key_width_6";
        bVar11.keyType = EnterKey.TAG;
        rowSchema2.keys = new C2944b[]{bVar7, bVar8, bVar9, bVar10, bVar11};
        this.mRows = new RowSchema[]{rowSchema, rowSchema2};
        this.verticalGap = "0px";
        this.slideThreshold = "fraction/key_slide_threshold";
        this.keyWidth = "20%p";
        this.keyHeight = "50%p";
        this.horizontalGap = "0px";
    }
}
