package com.cootek.smartinput5.p066ui.schema.template;

import com.cootek.smartinput5.engine.Settings;
import com.cootek.smartinput5.p066ui.EnterKey;
import com.cootek.smartinput5.p066ui.schema.C2944b;
import com.cootek.smartinput5.p066ui.schema.KeyboardSchema;
import com.cootek.smartinput5.p066ui.schema.RowSchema;

/* renamed from: com.cootek.smartinput5.ui.schema.template.T_chs_handwrite_half_international */
public class T_chs_handwrite_half_international extends KeyboardSchema {
    public T_chs_handwrite_half_international() {
        this.height = "fraction/hwhalf_keyboard_height";
        this.slipThreshold = "60%p";
        this.shadowRect = "0%p:0%p:100%p:82.5%p,0%p:82.5%p:15%p:100%p,25%p:82.5%p:100%p:100%p";
        this.supportSmileyAnimation = "false";
        RowSchema rowSchema = new RowSchema();
        rowSchema.rowEdgeFlags = "top";
        C2944b bVar = new C2944b();
        bVar.keyName = "sk_bk";
        bVar.backgroundType = "fun";
        bVar.keyIcon = "drawable/key_fore_backspace";
        bVar.keyEdgeFlags = Settings.KEYBOARD_MARGIN_RIGHT;
        bVar.horizontalGap = "fraction/handwrite_keyboard_gap";
        bVar.keyType = "BackSpaceKey";
        rowSchema.keys = new C2944b[]{bVar};
        RowSchema rowSchema2 = new RowSchema();
        C2944b bVar2 = new C2944b();
        bVar2.keyName = "Comma";
        bVar2.backgroundType = "fun";
        bVar2.keyEdgeFlags = Settings.KEYBOARD_MARGIN_RIGHT;
        bVar2.horizontalGap = "fraction/handwrite_keyboard_gap";
        bVar2.keyType = "Key";
        rowSchema2.keys = new C2944b[]{bVar2};
        RowSchema rowSchema3 = new RowSchema();
        C2944b bVar3 = new C2944b();
        bVar3.keyName = "Dot";
        bVar3.backgroundType = "fun";
        bVar3.keyEdgeFlags = Settings.KEYBOARD_MARGIN_RIGHT;
        bVar3.horizontalGap = "fraction/handwrite_keyboard_gap";
        bVar3.keyType = "Key";
        rowSchema3.keys = new C2944b[]{bVar3};
        RowSchema rowSchema4 = new RowSchema();
        C2944b bVar4 = new C2944b();
        bVar4.keyName = "QuestionMark";
        bVar4.backgroundType = "fun";
        bVar4.keyEdgeFlags = Settings.KEYBOARD_MARGIN_RIGHT;
        bVar4.horizontalGap = "fraction/handwrite_keyboard_gap";
        bVar4.keyType = "Key";
        rowSchema4.keys = new C2944b[]{bVar4};
        RowSchema rowSchema5 = new RowSchema();
        C2944b bVar5 = new C2944b();
        bVar5.keyName = "ExclamationMark";
        bVar5.backgroundType = "fun";
        bVar5.keyEdgeFlags = Settings.KEYBOARD_MARGIN_RIGHT;
        bVar5.horizontalGap = "fraction/handwrite_keyboard_gap";
        bVar5.keyType = "Key";
        rowSchema5.keys = new C2944b[]{bVar5};
        RowSchema rowSchema6 = new RowSchema();
        rowSchema6.rowEdgeFlags = "bottom";
        C2944b bVar6 = new C2944b();
        bVar6.keyName = "sk_sym";
        bVar6.backgroundType = "fun";
        bVar6.keyEdgeFlags = Settings.KEYBOARD_MARGIN_LEFT;
        bVar6.mainOnlyTextSize = "dimen/button_textsize";
        bVar6.keyWidth = "fraction/bottom_key_width_2";
        bVar6.keyType = "Key";
        C2944b bVar7 = new C2944b();
        bVar7.keyName = "sk_lng";
        bVar7.backgroundType = "fun";
        bVar7.triType = "opt_curve";
        bVar7.foregroundType = "fitCenter";
        bVar7.hasLongPressIcon = "true";
        bVar7.mainOnlyTextSize = "dimen/button_textsize";
        bVar7.keyWidth = "fraction/bottom_key_width_1";
        bVar7.keyType = "LanguageKey";
        C2944b bVar8 = new C2944b();
        bVar8.keyName = "sk_full";
        bVar8.backgroundType = "fun";
        bVar8.mainOnlyTextSize = "dimen/button_textsize";
        bVar8.keyWidth = "fraction/bottom_key_width_3";
        bVar8.keyType = "Key";
        C2944b bVar9 = new C2944b();
        bVar9.keyName = "sk_sp";
        bVar9.foregroundType = "fitCenter";
        bVar9.keyIcon = "@drawable/key_sp_normal";
        bVar9.iconPreview = "drawable/key_preview_space";
        bVar9.keyWidth = "@fraction/bottom_key_width_4";
        bVar9.altTextInCorner = "true";
        bVar9.keyType = "SpaceKey";
        C2944b bVar10 = new C2944b();
        bVar10.keyName = "sk_num";
        bVar10.backgroundType = "fun";
        bVar10.mainOnlyTextSize = "dimen/button_textsize";
        bVar10.keyWidth = "fraction/bottom_key_width_3";
        bVar10.keyType = "Key";
        C2944b bVar11 = new C2944b();
        bVar11.keyName = "sk_ent";
        bVar11.backgroundType = "fun";
        bVar11.keyIcon = "@drawable/key_fore_enter";
        bVar11.keyEdgeFlags = Settings.KEYBOARD_MARGIN_RIGHT;
        bVar11.mainOnlyTextSize = "dimen/button_textsize";
        bVar11.keyWidth = "fraction/handwrite_keyboard_default_key_width";
        bVar11.keyType = EnterKey.TAG;
        rowSchema6.keys = new C2944b[]{bVar6, bVar7, bVar8, bVar9, bVar10, bVar11};
        rowSchema6.keyHeight = "17.5%p";
        this.mRows = new RowSchema[]{rowSchema, rowSchema2, rowSchema3, rowSchema4, rowSchema5, rowSchema6};
        this.verticalGap = "0px";
        this.slideThreshold = "fraction/key_slide_threshold";
        this.keyWidth = "fraction/handwrite_keyboard_default_key_width";
        this.keyHeight = "16.5%p";
        this.horizontalGap = "0px";
    }
}
