package com.cootek.smartinput5.p066ui.schema.template;

import com.cootek.smartinput5.engine.Settings;
import com.cootek.smartinput5.p066ui.schema.C2944b;
import com.cootek.smartinput5.p066ui.schema.KeyboardSchema;
import com.cootek.smartinput5.p066ui.schema.RowSchema;

/* renamed from: com.cootek.smartinput5.ui.schema.template.T_filters */
public class T_filters extends KeyboardSchema {
    public T_filters() {
        this.height = "@fraction/keyboard_height";
        this.width = "15%p";
        this.slipThreshold = "60%p";
        this.enableDrawMoveContrail = "false";
        RowSchema rowSchema = new RowSchema();
        rowSchema.rowEdgeFlags = "top";
        C2944b bVar = new C2944b();
        bVar.keyType = "Filter";
        bVar.filterIndex = "0";
        rowSchema.keys = new C2944b[]{bVar};
        RowSchema rowSchema2 = new RowSchema();
        C2944b bVar2 = new C2944b();
        bVar2.keyType = "Filter";
        bVar2.filterIndex = "1";
        rowSchema2.keys = new C2944b[]{bVar2};
        RowSchema rowSchema3 = new RowSchema();
        C2944b bVar3 = new C2944b();
        bVar3.keyType = "Filter";
        bVar3.filterIndex = "2";
        rowSchema3.keys = new C2944b[]{bVar3};
        RowSchema rowSchema4 = new RowSchema();
        C2944b bVar4 = new C2944b();
        bVar4.keyType = "Filter";
        bVar4.filterIndex = "3";
        rowSchema4.keys = new C2944b[]{bVar4};
        RowSchema rowSchema5 = new RowSchema();
        C2944b bVar5 = new C2944b();
        bVar5.keyType = "Filter";
        bVar5.filterIndex = "4";
        rowSchema5.keys = new C2944b[]{bVar5};
        RowSchema rowSchema6 = new RowSchema();
        C2944b bVar6 = new C2944b();
        bVar6.keyType = "Filter";
        bVar6.filterIndex = "5";
        rowSchema6.keys = new C2944b[]{bVar6};
        RowSchema rowSchema7 = new RowSchema();
        C2944b bVar7 = new C2944b();
        bVar7.keyType = "Filter";
        bVar7.filterIndex = "6";
        rowSchema7.keys = new C2944b[]{bVar7};
        RowSchema rowSchema8 = new RowSchema();
        C2944b bVar8 = new C2944b();
        bVar8.keyType = "Filter";
        bVar8.filterIndex = "7";
        rowSchema8.keys = new C2944b[]{bVar8};
        RowSchema rowSchema9 = new RowSchema();
        C2944b bVar9 = new C2944b();
        bVar9.keyType = "Filter";
        bVar9.filterIndex = "8";
        rowSchema9.keys = new C2944b[]{bVar9};
        RowSchema rowSchema10 = new RowSchema();
        C2944b bVar10 = new C2944b();
        bVar10.keyType = "Filter";
        bVar10.filterIndex = "9";
        rowSchema10.keys = new C2944b[]{bVar10};
        RowSchema rowSchema11 = new RowSchema();
        C2944b bVar11 = new C2944b();
        bVar11.keyType = "Filter";
        bVar11.filterIndex = "10";
        rowSchema11.keys = new C2944b[]{bVar11};
        RowSchema rowSchema12 = new RowSchema();
        C2944b bVar12 = new C2944b();
        bVar12.keyType = "Filter";
        bVar12.filterIndex = "11";
        rowSchema12.keys = new C2944b[]{bVar12};
        RowSchema rowSchema13 = new RowSchema();
        C2944b bVar13 = new C2944b();
        bVar13.keyType = "Filter";
        bVar13.filterIndex = "12";
        rowSchema13.keys = new C2944b[]{bVar13};
        RowSchema rowSchema14 = new RowSchema();
        C2944b bVar14 = new C2944b();
        bVar14.keyType = "Filter";
        bVar14.filterIndex = "13";
        rowSchema14.keys = new C2944b[]{bVar14};
        RowSchema rowSchema15 = new RowSchema();
        C2944b bVar15 = new C2944b();
        bVar15.keyType = "Filter";
        bVar15.filterIndex = "14";
        rowSchema15.keys = new C2944b[]{bVar15};
        RowSchema rowSchema16 = new RowSchema();
        C2944b bVar16 = new C2944b();
        bVar16.keyType = "Filter";
        bVar16.filterIndex = "15";
        rowSchema16.keys = new C2944b[]{bVar16};
        this.mRows = new RowSchema[]{rowSchema, rowSchema2, rowSchema3, rowSchema4, rowSchema5, rowSchema6, rowSchema7, rowSchema8, rowSchema9, rowSchema10, rowSchema11, rowSchema12, rowSchema13, rowSchema14, rowSchema15, rowSchema16};
        this.verticalGap = "0px";
        this.slideThreshold = "100%p";
        this.ignoreStroke = "true";
        this.keyEdgeFlags = Settings.KEYBOARD_MARGIN_LEFT;
        this.supportPreviewPopup = "false";
        this.keyWidth = "100%p";
        this.keyHeight = "19%p";
        this.horizontalGap = "0px";
    }
}
