package com.cootek.smartinput5.p066ui.schema.template;

import com.cootek.smartinput5.engine.Settings;
import com.cootek.smartinput5.p066ui.schema.C2944b;
import com.cootek.smartinput5.p066ui.schema.KeyboardSchema;
import com.cootek.smartinput5.p066ui.schema.RowSchema;

/* renamed from: com.cootek.smartinput5.ui.schema.template.T_soft_full_keyboard_sub_schema */
public class T_soft_full_keyboard_sub_schema extends KeyboardSchema {
    public T_soft_full_keyboard_sub_schema() {
        this.height = "@fraction/keyboard_height";
        this.slipThreshold = "60%p";
        this.hasDictSwitcher = "true";
        RowSchema rowSchema = new RowSchema();
        C2944b bVar = new C2944b();
        bVar.keyName = "sk_sub_1_1";
        bVar.mainTitleRef = "W";
        bVar.ignoreCurve = "true";
        bVar.ignoreStroke = "true";
        bVar.keyEdgeFlags = Settings.KEYBOARD_MARGIN_LEFT;
        bVar.keyWidth = "10%p";
        bVar.keyType = "Key";
        C2944b bVar2 = new C2944b();
        bVar2.keyName = "sk_sub_1_2";
        bVar2.mainTitleRef = "W";
        bVar2.ignoreCurve = "true";
        bVar2.ignoreStroke = "true";
        bVar2.keyWidth = "10%p";
        bVar2.keyType = "Key";
        C2944b bVar3 = new C2944b();
        bVar3.keyName = "sk_sub_1_3";
        bVar3.mainTitleRef = "W";
        bVar3.ignoreCurve = "true";
        bVar3.ignoreStroke = "true";
        bVar3.keyWidth = "10%p";
        bVar3.keyType = "Key";
        C2944b bVar4 = new C2944b();
        bVar4.keyName = "sk_sub_1_4";
        bVar4.mainTitleRef = "W";
        bVar4.ignoreCurve = "true";
        bVar4.ignoreStroke = "true";
        bVar4.keyWidth = "10%p";
        bVar4.keyType = "Key";
        C2944b bVar5 = new C2944b();
        bVar5.keyName = "sk_sub_1_5";
        bVar5.mainTitleRef = "W";
        bVar5.ignoreCurve = "true";
        bVar5.ignoreStroke = "true";
        bVar5.keyWidth = "10%p";
        bVar5.keyType = "Key";
        C2944b bVar6 = new C2944b();
        bVar6.keyName = "sk_sub_1_6";
        bVar6.mainTitleRef = "W";
        bVar6.ignoreCurve = "true";
        bVar6.ignoreStroke = "true";
        bVar6.keyWidth = "10%p";
        bVar6.keyType = "Key";
        C2944b bVar7 = new C2944b();
        bVar7.keyName = "sk_sub_1_7";
        bVar7.mainTitleRef = "W";
        bVar7.ignoreCurve = "true";
        bVar7.ignoreStroke = "true";
        bVar7.keyWidth = "10%p";
        bVar7.keyType = "Key";
        C2944b bVar8 = new C2944b();
        bVar8.keyName = "sk_sub_1_8";
        bVar8.mainTitleRef = "W";
        bVar8.ignoreCurve = "true";
        bVar8.ignoreStroke = "true";
        bVar8.keyWidth = "10%p";
        bVar8.keyType = "Key";
        C2944b bVar9 = new C2944b();
        bVar9.keyName = "sk_sub_1_9";
        bVar9.mainTitleRef = "W";
        bVar9.ignoreCurve = "true";
        bVar9.ignoreStroke = "true";
        bVar9.keyWidth = "10%p";
        bVar9.keyType = "Key";
        C2944b bVar10 = new C2944b();
        bVar10.keyName = "sk_sub_1_10";
        bVar10.mainTitleRef = "W";
        bVar10.ignoreCurve = "true";
        bVar10.ignoreStroke = "true";
        bVar10.keyEdgeFlags = Settings.KEYBOARD_MARGIN_RIGHT;
        bVar10.keyWidth = "10%p";
        bVar10.keyType = "Key";
        rowSchema.keys = new C2944b[]{bVar, bVar2, bVar3, bVar4, bVar5, bVar6, bVar7, bVar8, bVar9, bVar10};
        this.mRows = new RowSchema[]{rowSchema};
        this.verticalGap = "0px";
        this.slideThreshold = "@fraction/key_slide_threshold";
        this.altTextSize = "@dimen/keyboard_alt_text_size_small";
        this.keyWidth = "10%p";
        this.keyHeight = "25%p";
        this.horizontalGap = "0px";
        this.altTextInCorner = "@bool/full_keyboard_text_layout_in_corner";
    }
}
